# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WTRZGeJ_A0A5TzEkJip9eNjk22PnqgHk
"""

word = input('Введите слово: ')
number = int(input('Введите номер удаляемой буквы: ')) - 1

word_list = list(word) #Слово, разбитое на буквы
delete_letter = word_list[number] #Удаляемая буква 
size = len(word_list) #Размер слова после подсчета букв word_list
new_word_list = [] #Разбитое слово без удаляемой буквы
for i in range(0,size): 
  if delete_letter != word_list[i]: 
    new_word_list.append(word_list[i]) #Сохранение всех букв, не совпадающих от удаляемой буквы 
print(''.join(new_word_list))